// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ghazimuharam/twitter-bot/cmd/config/entity"
	"github.com/ghazimuharam/twitter-bot/internal/twitter/delivery/cron"
)

// Injectors from wire.go:

func InitCronApp(configs *entity.Config) *cron.CronApplication {
	client := provideTwitterClient(configs)
	directMessageRepo := provideDirectMessageRepo(configs, client)
	cacheRepo := provideCacheRepo(configs)
	directMessageUsecase := provideDirectMessageUsecase(directMessageRepo, cacheRepo, configs)
	tweetRepo := provideTweetRepo(client, configs)
	tweetUsecase := provideTweetUsecase(tweetRepo)
	mediaRepo := provideMediaRepo(client, configs)
	mediaUsecase := provideMediaUsecase(mediaRepo)
	cronUsecase := provideCronUsecase(configs, directMessageUsecase, tweetUsecase, mediaUsecase, cacheRepo)
	cronApplication := provideCronApplication(cronUsecase, configs)
	return cronApplication
}
